### ISSUE TITLE
Crash on tapping a foriegn key cell

### ISSUE THREAD

**Issue by daxfrost** [hankinsoft/SQLPro-iOS#11]
In result sets that have foriegn columns there is a foriegn key arrow linking to the table or record, tapping on this causes a crash.

**Comment by hankinsoft** [comment]
Sorry for the delay on replay - which type of database are you connecting to? (MSSQL, MySQL, other)?

**Comment by daxfrost** [comment]
Np, I am using Postgres

**Comment by hankinsoft** [comment]
I've updated SQLPro for Postgres and it should sort this issue out - if you get the chance, could you give it a try?

**Comment by daxfrost** [comment]
Fixed! Thank you
