### ISSUE TITLE
SSH server host key / fingerprint could not be verified

### ISSUE THREAD

**Issue by mladenmarkov** [hankinsoft/SQLPro-iOS#3]
I’m getting this when I try to connect to MariaDB via SSH tunnel. I can connect from terminal (macOS, Linux) and Java alright. The server’s SSH keys are fine.

The log file doesn’s say much more
`2017/11/19 12:50:56:651  SSH tunnel failed after 3.07 seconds with error: SSH server host key / fingerprint could not be verified.`

Do I need any additional configuration?

Cheers
Mladen

![1a95eab5-8aa3-4600-9f47-138754bc788e](https://user-images.githubusercontent.com/1222170/32987566-54c96884-cd2a-11e7-852e-1e4f36e88ad3.jpeg)
![5a808fbe-31af-453c-b051-7e6ef1d99ffc](https://user-images.githubusercontent.com/1222170/32987567-57997fcc-cd2a-11e7-89a9-1af06e776e92.jpeg)

**Comment by hankinsoft** [comment]
Hmm, that’s odd. And every time you connect, you get the same trust ssh
fingerprint message? It’s always the same fingerprint displayed as well?

Cheers,
Kyle

**Comment by mladenmarkov** [comment]
It's the same fingerprint, over and over. And I do click Trust every time =)
Tried on both my iPhone and iPad

**Comment by hankinsoft** [comment]
Thanks! For the ssh host, are you entering a host name or an ip address? If
host name, is it the IP address appearing in the trust dialog? If so, could
you try entering the IP address rather than host name and see if that
fixed? I’ll also work on adding some additional diagnostic code for a build
early next week in case that’s not the issue.

**Comment by mladenmarkov** [comment]
I was entering a hostname. And the trust dialog showed the hostname and not the ip address. When I changed the configuration to ip, it worked right away -- the dialog displayed the ip address and the connection was successful. Don't know why the hostname is causing an issue. 

There are other issues too, but I'll report them separately when I find the time

**Comment by hankinsoft** [comment]
Awesome, thanks for letting me know. I’ll work on a fix for this early this
werk. As you get the chance, I would love to hear about the other issues.

Cheers,
Kyle

**Comment by hankinsoft** [comment]
Hi! Just wanted to note that the fix for this is now live on the App Store.
If you get the chance, please give it a try and let me know if everything
is sorted out!

**Comment by mladenmarkov** [comment]
Unfortunately it doesn’t seem to be fixed. I completely removed the app and installed it again, so to clear any data it may have stored.

Now when I create a new connection with a hostname, it does seem to connect, at least no error messages are displayed. However, it can neither browse the databases, nor the tables. When I manually enter a database name and then try to run a query, I get the same error that the fingerprint cannot be verified.

I can send you the logs and screenshots privately, as I wouldn’t want to upload them here

**Comment by hankinsoft** [comment]
Hi! Just wanted to note that I have a new build out that:
1. I think fixes the issue.
2. Includes extra logging incase it does not.

If you still see it, could you email me a few screenshots & the log? To
kyle@hankinsoft.com.

Thanks!

**Comment by hankinsoft** [comment]
I think we sorted this through email? If you get the chance, could you confirm?
