### ISSUE TITLE
Screen keyboard pops up even when hardware keyboard is attached

### ISSUE THREAD

**Issue by fonnesbeck** [hankinsoft/SQLPro-iOS#8]
When selecting an input for writing queries, the iOS software keyboard pops up even when the Apple keyboard is attached. This does not occur on other apps, so I am assuming this is a SQLPro bug.

Running on the latest iOS on a 2018 iPad Pro.

**Comment by hankinsoft** [comment]
Could you try rebooting your iPad and reconnecting/disconnecing the
keyboard?  To my knowledge iOS handles this internally and is not
controlled by individual apps.

**Comment by fonnesbeck** [comment]
That does not (permanently) fix the issue, but I do understand now that it is not app-related. I will close this.
